// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto2020.Data;

namespace Projeto2020.Migrations
{
    [DbContext(typeof(Projeto2020Context))]
    [Migration("20200202043221_NewClassSetor")]
    partial class NewClassSetor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto2020.Models.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<float>("Preco");

                    b.Property<int?>("SetorId");

                    b.Property<int>("Status");

                    b.HasKey("Codigo");

                    b.HasIndex("SetorId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Projeto2020.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("Id");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("Projeto2020.Models.Produto", b =>
                {
                    b.HasOne("Projeto2020.Models.Setor", "Setor")
                        .WithMany("Produtos")
                        .HasForeignKey("SetorId");
                });
#pragma warning restore 612, 618
        }
    }
}
